### ISSUE TITLE
nothing to do with OkamiStation everthing to do with Creating Space

### ISSUE THREAD

**Issue by RealAntEngineer** [TalonFloof/OkamiStation#2]
Hey,

Did you think I was dead ?

**Comment by RealAntEngineer** [comment]
![Capture d'écran 2024-07-16 012301](https://github.com/user-attachments/assets/9f80bb8a-3fdd-4733-87ec-8c297855504b)

**Comment by TalonFloof** [comment]
Honestly, I just messed around with the code and stuff, I don't really have any plans to continue with it.
